using System.IO;
using DiskSpaceInspector.Core.Models;

namespace DiskSpaceInspector.App.ViewModels;

internal sealed record DemoData(
    IReadOnlyList<VolumeInfo> Volumes,
    ScanResult Scan,
    IReadOnlyList<CleanupFinding> CleanupFindings,
    IReadOnlyList<StorageRelationship> Relationships,
    IReadOnlyList<ChangeRecord> Changes,
    IReadOnlyList<InsightFinding> Insights,
    IReadOnlyList<AiCleanupRecommendation> AiRecommendations);

internal static class DemoDataFactory
{
    public static DemoData Create()
    {
        var scanId = Guid.NewGuid();
        var now = DateTimeOffset.UtcNow;
        var nodes = BuildNodes(now);
        var root = nodes[0];
        var findings = BuildFindings(nodes, now);
        var relationships = BuildRelationships(scanId, nodes);
        var changes = BuildChanges(scanId, nodes);
        var insights = BuildInsights(scanId, findings, relationships);
        var aiRecommendations = BuildAiRecommendations(findings);

        var scan = new ScanResult
        {
            Session = new ScanSession
            {
                Id = scanId,
                RootPath = root.FullPath,
                StartedAtUtc = now.AddMinutes(-7),
                CompletedAtUtc = now,
                Status = ScanStatus.Completed,
                TotalLogicalBytes = root.TotalLength,
                TotalPhysicalBytes = root.TotalPhysicalLength,
                FilesScanned = 5_210_348,
                DirectoriesScanned = 1_420_774,
                IssueCount = 3
            },
            Volume = new VolumeInfo
            {
                Name = "Windows",
                Label = "Windows",
                RootPath = @"C:\",
                FileSystem = "NTFS",
                VolumeSerial = "DEMO-C",
                DriveType = "Fixed",
                IsReady = true,
                TotalBytes = GiB(952),
                FreeBytes = GiB(140)
            },
            Nodes = nodes,
            Edges =
            [
                new FileSystemEdge
                {
                    Id = 1,
                    SourceNodeId = NodeId(nodes, @"C:\Users\demo\OneDrive"),
                    TargetPath = "OneDrive cloud storage",
                    Kind = FileSystemEdgeKind.AppOwnership,
                    Label = "synced by",
                    Evidence = "Cloud sync root detected from path and attributes"
                },
                new FileSystemEdge
                {
                    Id = 2,
                    SourceNodeId = NodeId(nodes, @"C:\Projects\shop-ui\node_modules"),
                    TargetPath = @"C:\Projects\shop-ui\package.json",
                    Kind = FileSystemEdgeKind.PackageArtifact,
                    Label = "generated by",
                    Evidence = "Node package manifest in parent project"
                }
            ],
            Issues =
            [
                new ScanIssue
                {
                    Id = 1,
                    Path = @"C:\System Volume Information",
                    Operation = "Enumerate",
                    Message = "Access denied. Run elevated for exact restore point sizing.",
                    ElevationMayHelp = true,
                    OccurredAtUtc = now
                },
                new ScanIssue
                {
                    Id = 2,
                    Path = @"C:\Windows\CSC",
                    Operation = "Enumerate",
                    Message = "Offline files cache is protected by Windows.",
                    ElevationMayHelp = true,
                    OccurredAtUtc = now
                },
                new ScanIssue
                {
                    Id = 3,
                    Path = @"C:\Program Files\WindowsApps",
                    Operation = "Enumerate",
                    Message = "Package folder metadata is partially restricted.",
                    ElevationMayHelp = true,
                    OccurredAtUtc = now
                }
            ]
        };

        return new DemoData(
            [
                scan.Volume,
                new VolumeInfo
                {
                    Name = "Data",
                    Label = "Projects",
                    RootPath = @"D:\",
                    FileSystem = "NTFS",
                    VolumeSerial = "DEMO-D",
                    DriveType = "Fixed",
                    IsReady = true,
                    TotalBytes = GiB(1_812),
                    FreeBytes = GiB(976)
                },
                new VolumeInfo
                {
                    Name = "Backup",
                    Label = "Archive",
                    RootPath = @"E:\",
                    FileSystem = "exFAT",
                    VolumeSerial = "DEMO-E",
                    DriveType = "Removable",
                    IsReady = true,
                    TotalBytes = GiB(3_725),
                    FreeBytes = GiB(1_620)
                }
            ],
            scan,
            findings,
            relationships,
            changes,
            insights,
            aiRecommendations);
    }

    private static List<FileSystemNode> BuildNodes(DateTimeOffset now)
    {
        var nodes = new List<FileSystemNode>();
        Add(nodes, 1, null, "Windows (C:)", @"C:\", FileSystemNodeKind.Drive, GiB(812), 5_210_348, 1_420_774, "Drive", now.AddMinutes(-2), 0);

        Add(nodes, 10, 1, "Users", @"C:\Users", FileSystemNodeKind.Directory, GiB(231), 1_730_400, 318_200, "Folder", now.AddDays(-1), 1);
        Add(nodes, 11, 1, "Projects", @"C:\Projects", FileSystemNodeKind.Directory, GiB(167), 1_284_910, 206_440, "Code", now.AddHours(-2), 1);
        Add(nodes, 12, 1, "Windows", @"C:\Windows", FileSystemNodeKind.Directory, GiB(151), 642_500, 95_210, "System", now.AddDays(-1), 1);
        Add(nodes, 13, 1, "Program Files", @"C:\Program Files", FileSystemNodeKind.Directory, GiB(118), 433_240, 55_730, "Installer", now.AddDays(-3), 1);
        Add(nodes, 14, 1, "ProgramData", @"C:\ProgramData", FileSystemNodeKind.Directory, GiB(82), 251_330, 39_120, "Folder", now.AddDays(-4), 1);
        Add(nodes, 15, 1, "$Recycle.Bin", @"C:\$Recycle.Bin", FileSystemNodeKind.Directory, GiB(38), 18_210, 3_420, "Temporary", now.AddDays(-17), 1);
        Add(nodes, 16, 1, "pagefile.sys", @"C:\pagefile.sys", FileSystemNodeKind.File, GiB(31.5), 1, 0, "System", now.AddHours(-1), 1, ".sys");
        Add(nodes, 17, 1, "hiberfil.sys", @"C:\hiberfil.sys", FileSystemNodeKind.File, GiB(25), 1, 0, "System", now.AddHours(-1), 1, ".sys");

        Add(nodes, 100, 10, "demo", @"C:\Users\demo", FileSystemNodeKind.Directory, GiB(228), 1_704_100, 312_000, "Folder", now.AddHours(-3), 2);
        Add(nodes, 101, 100, "Downloads", @"C:\Users\demo\Downloads", FileSystemNodeKind.Directory, GiB(84), 6_412, 220, "Archive", now.AddDays(-40), 3);
        Add(nodes, 102, 100, "OneDrive", @"C:\Users\demo\OneDrive", FileSystemNodeKind.Directory, GiB(53), 83_100, 14_300, "Folder", now.AddHours(-8), 3);
        Add(nodes, 103, 100, "Videos", @"C:\Users\demo\Videos", FileSystemNodeKind.Directory, GiB(42), 1_184, 84, "Video", now.AddDays(-70), 3);
        Add(nodes, 104, 100, "Pictures", @"C:\Users\demo\Pictures", FileSystemNodeKind.Directory, GiB(31), 18_400, 620, "Image", now.AddDays(-33), 3);
        Add(nodes, 105, 100, "AppData", @"C:\Users\demo\AppData", FileSystemNodeKind.Directory, GiB(18), 1_588_000, 291_000, "Temporary", now.AddHours(-1), 3);
        Add(nodes, 106, 105, "Temp", @"C:\Users\demo\AppData\Local\Temp", FileSystemNodeKind.Directory, GiB(7.9), 91_220, 9_100, "Temporary", now.AddDays(-8), 4);
        Add(nodes, 107, 105, "Chrome Cache", @"C:\Users\demo\AppData\Local\Google\Chrome\User Data\Default\Cache", FileSystemNodeKind.Directory, GiB(5.2), 244_500, 16_400, "Temporary", now.AddHours(-6), 4);
        Add(nodes, 108, 105, "NuGet cache", @"C:\Users\demo\.nuget\packages", FileSystemNodeKind.Directory, GiB(4.1), 83_500, 19_100, "Code", now.AddDays(-12), 4);
        Add(nodes, 109, 101, "WindowsDevKit.iso", @"C:\Users\demo\Downloads\WindowsDevKit.iso", FileSystemNodeKind.File, GiB(8.2), 1, 0, "Archive", now.AddDays(-190), 4, ".iso");
        Add(nodes, 110, 101, "visual-studio-build-tools.exe", @"C:\Users\demo\Downloads\visual-studio-build-tools.exe", FileSystemNodeKind.File, GiB(6.5), 1, 0, "Installer", now.AddDays(-132), 4, ".exe");
        Add(nodes, 111, 101, "client-export-2025.zip", @"C:\Users\demo\Downloads\client-export-2025.zip", FileSystemNodeKind.File, GiB(12.4), 1, 0, "Archive", now.AddDays(-94), 4, ".zip");
        Add(nodes, 112, 103, "screen-recording.mov", @"C:\Users\demo\Videos\screen-recording.mov", FileSystemNodeKind.File, GiB(18.8), 1, 0, "Video", now.AddDays(-76), 4, ".mov");
        Add(nodes, 113, 104, "raw-photo-session.zip", @"C:\Users\demo\Pictures\raw-photo-session.zip", FileSystemNodeKind.File, GiB(11.2), 1, 0, "Image", now.AddDays(-420), 4, ".zip");

        Add(nodes, 200, 11, "shop-ui", @"C:\Projects\shop-ui", FileSystemNodeKind.Directory, GiB(73), 488_000, 83_200, "Code", now.AddHours(-2), 2);
        Add(nodes, 201, 200, "node_modules", @"C:\Projects\shop-ui\node_modules", FileSystemNodeKind.Directory, GiB(46), 411_000, 77_000, "Code", now.AddDays(-6), 3);
        Add(nodes, 202, 200, ".next", @"C:\Projects\shop-ui\.next", FileSystemNodeKind.Directory, GiB(8.4), 28_200, 1_940, "Code", now.AddHours(-4), 3);
        Add(nodes, 203, 11, ".gradle", @"C:\Projects\.gradle", FileSystemNodeKind.Directory, GiB(25), 114_000, 22_500, "Code", now.AddDays(-22), 2);
        Add(nodes, 204, 11, ".venv", @"C:\Projects\data-pipeline\.venv", FileSystemNodeKind.Directory, GiB(17), 251_000, 47_000, "Code", now.AddDays(-14), 2);
        Add(nodes, 205, 11, "Docker", @"C:\Projects\docker-data", FileSystemNodeKind.Directory, GiB(31), 12_430, 2_200, "Archive", now.AddHours(-11), 2);
        Add(nodes, 206, 202, "app.bundle.js", @"C:\Projects\shop-ui\.next\static\app.bundle.js", FileSystemNodeKind.File, GiB(2.2), 1, 0, "Code", now.AddHours(-4), 4, ".js");
        Add(nodes, 207, 205, "dev-postgres-backup.bak", @"C:\Projects\docker-data\dev-postgres-backup.bak", FileSystemNodeKind.File, GiB(21.5), 1, 0, "Archive", now.AddDays(-48), 3, ".bak");
        Add(nodes, 208, 205, "linux-builder.vhdx", @"C:\Projects\docker-data\linux-builder.vhdx", FileSystemNodeKind.File, GiB(27.8), 1, 0, "Archive", now.AddDays(-16), 3, ".vhdx");

        Add(nodes, 300, 12, "SoftwareDistribution", @"C:\Windows\SoftwareDistribution\Download", FileSystemNodeKind.Directory, GiB(18.6), 71_200, 4_300, "System", now.AddDays(-9), 2);
        Add(nodes, 301, 12, "WinSxS", @"C:\Windows\WinSxS", FileSystemNodeKind.Directory, GiB(29), 214_300, 38_000, "System", now.AddHours(-9), 2);
        Add(nodes, 302, 12, "Logs", @"C:\Windows\Logs", FileSystemNodeKind.Directory, GiB(4.6), 12_500, 1_100, "Temporary", now.AddDays(-31), 2);

        Add(nodes, 400, 13, "WindowsApps", @"C:\Program Files\WindowsApps", FileSystemNodeKind.Directory, GiB(44), 182_000, 18_500, "System", now.AddDays(-2), 2);
        Add(nodes, 401, 13, "Microsoft Visual Studio", @"C:\Program Files\Microsoft Visual Studio", FileSystemNodeKind.Directory, GiB(28), 97_000, 12_300, "Installer", now.AddDays(-5), 2);
        Add(nodes, 402, 13, "Game SDKs", @"C:\Program Files\Game SDKs", FileSystemNodeKind.Directory, GiB(19), 9_400, 910, "Archive", now.AddDays(-80), 2);

        Add(nodes, 500, 14, "Package Cache", @"C:\ProgramData\Package Cache", FileSystemNodeKind.Directory, GiB(22), 13_500, 1_430, "Installer", now.AddDays(-120), 2);
        Add(nodes, 501, 14, "DockerDesktop", @"C:\ProgramData\DockerDesktop", FileSystemNodeKind.Directory, GiB(28), 18_000, 2_900, "Archive", now.AddDays(-3), 2);
        Add(nodes, 502, 14, "NVIDIA", @"C:\ProgramData\NVIDIA Corporation\Downloader", FileSystemNodeKind.Directory, GiB(7.4), 1_200, 100, "Installer", now.AddDays(-55), 2);

        return nodes;
    }

    private static IReadOnlyList<CleanupFinding> BuildFindings(IReadOnlyList<FileSystemNode> nodes, DateTimeOffset now)
    {
        return
        [
            Finding(nodes, @"C:\Users\demo\AppData\Local\Temp", "Temporary files", CleanupSafety.Safe, CleanupActionKind.ClearCache, 0.96, "Old temp files can usually be cleared after apps are closed.", "LocalAppDataTemp", "Windows user profile", now),
            Finding(nodes, @"C:\$Recycle.Bin", "Recycle Bin", CleanupSafety.Safe, CleanupActionKind.EmptyRecycleBin, 0.98, "Recycle Bin content is staged for review before emptying.", "RecycleBin", "Windows shell", now),
            Finding(nodes, @"C:\Users\demo\AppData\Local\Google\Chrome\User Data\Default\Cache", "Application cache", CleanupSafety.Safe, CleanupActionKind.ClearCache, 0.9, "Browser cache can be recreated; active profile databases are not targeted.", "ChromeCache", "Google Chrome", now),
            Finding(nodes, @"C:\Projects\shop-ui\node_modules", "Developer artifact", CleanupSafety.Review, CleanupActionKind.ClearCache, 0.84, "Generated dependency folder. Reinstall with package manager if still needed.", "NodeModules", "npm project", now),
            Finding(nodes, @"C:\Projects\shop-ui\.next", "Developer artifact", CleanupSafety.Safe, CleanupActionKind.ClearCache, 0.92, "Generated Next.js build cache.", "NextBuildCache", "Next.js", now),
            Finding(nodes, @"C:\Projects\.gradle", "Developer artifact", CleanupSafety.Review, CleanupActionKind.ClearCache, 0.82, "Gradle cache may be regenerated but can slow the next build.", "GradleCache", "Gradle", now),
            Finding(nodes, @"C:\Users\demo\Downloads", "Downloads review", CleanupSafety.Review, CleanupActionKind.ReviewDownloads, 0.72, "Large downloads, installers, and archives need manual review.", "DownloadsLargeOld", "User files", now),
            Finding(nodes, @"C:\Windows\SoftwareDistribution\Download", "Windows cleanup", CleanupSafety.UseSystemCleanup, CleanupActionKind.RunSystemCleanup, 0.94, "Windows Update cache should be cleared through official Windows cleanup routes.", "WindowsUpdateCache", "Windows Update", now),
            Finding(nodes, @"C:\ProgramData\Package Cache", "Installer cache", CleanupSafety.Review, CleanupActionKind.ArchiveOrMove, 0.62, "Installer cache can be required for repair/uninstall workflows.", "PackageCache", "Windows Installer", now),
            Finding(nodes, @"C:\Windows\WinSxS", "System managed storage", CleanupSafety.Blocked, CleanupActionKind.LeaveAlone, 1.0, "Component store is blocked from direct cleanup. Use DISM or Windows cleanup.", "BlockedSystemPath", "Windows", now),
            Finding(nodes, @"C:\pagefile.sys", "System file", CleanupSafety.Blocked, CleanupActionKind.LeaveAlone, 1.0, "Pagefile is actively managed by Windows and cannot be deleted by this app.", "BlockedSystemFile", "Windows", now)
        ];
    }

    private static IReadOnlyList<StorageRelationship> BuildRelationships(Guid scanId, IReadOnlyList<FileSystemNode> nodes)
    {
        return
        [
            Relationship(scanId, nodes, @"C:\Projects\shop-ui\node_modules", @"C:\Projects\shop-ui\package.json", FileSystemEdgeKind.PackageArtifact, "generated by", "npm", "package.json detected in parent project", 0.94),
            Relationship(scanId, nodes, @"C:\Projects\shop-ui\.next", @"C:\Projects\shop-ui\next.config.js", FileSystemEdgeKind.PackageArtifact, "generated by", "Next.js", "Next.js build output pattern", 0.92),
            Relationship(scanId, nodes, @"C:\Users\demo\AppData\Local\Google\Chrome\User Data\Default\Cache", "Google Chrome", FileSystemEdgeKind.CacheOwnership, "cache of", "Chrome", "Known browser cache location", 0.9),
            Relationship(scanId, nodes, @"C:\ProgramData\DockerDesktop", "Docker Desktop", FileSystemEdgeKind.AppOwnership, "owned by", "Docker", "Known Docker Desktop data root", 0.86),
            Relationship(scanId, nodes, @"C:\Users\demo\OneDrive", "OneDrive cloud storage", FileSystemEdgeKind.AppOwnership, "synced by", "OneDrive", "Cloud sync root naming and attributes", 0.78)
        ];
    }

    private static IReadOnlyList<ChangeRecord> BuildChanges(Guid scanId, IReadOnlyList<FileSystemNode> nodes)
    {
        return
        [
            Change(scanId, nodes, @"C:\Projects\shop-ui\node_modules", ChangeKind.Modified, GiB(34), GiB(46), "Dependencies grew after package update"),
            Change(scanId, nodes, @"C:\Users\demo\Downloads", ChangeKind.Modified, GiB(91), GiB(84), "Old installer cleanup reduced downloads"),
            Change(scanId, nodes, @"C:\ProgramData\DockerDesktop", ChangeKind.Added, 0, GiB(28), "Docker images were created since previous scan"),
            Change(scanId, nodes, @"C:\Windows\SoftwareDistribution\Download", ChangeKind.Modified, GiB(7), GiB(18.6), "Windows Update cache grew"),
            Change(scanId, nodes, @"C:\Users\demo\AppData\Local\Temp", ChangeKind.Modified, GiB(12), GiB(7.9), "Temp cleanup reduced local temp files")
        ];
    }

    private static IReadOnlyList<InsightFinding> BuildInsights(
        Guid scanId,
        IReadOnlyList<CleanupFinding> findings,
        IReadOnlyList<StorageRelationship> relationships)
    {
        var insights = new List<InsightFinding>();
        insights.AddRange(findings.Select(f => new InsightFinding
        {
            ScanId = scanId,
            NodeId = f.NodeId,
            Path = f.Path,
            Tool = f.Category switch
            {
                "Developer artifact" => "Developer Bloat Finder",
                "Windows cleanup" or "System managed storage" or "System file" => "System Storage Advisor",
                "Downloads review" => "Large File Triage",
                _ => "Cleanup Advisor"
            },
            Title = f.Category,
            Description = f.Explanation,
            Safety = f.Safety,
            RecommendedAction = f.RecommendedAction,
            SizeBytes = f.SizeBytes,
            Confidence = f.Confidence,
            Evidence = f.MatchedRule
        }));

        insights.AddRange(relationships.Select(r => new InsightFinding
        {
            ScanId = scanId,
            NodeId = r.SourceNodeId,
            Path = r.SourcePath,
            Tool = r.Kind is FileSystemEdgeKind.AppOwnership or FileSystemEdgeKind.CacheOwnership ? "App Ownership View" : "Storage Graph",
            Title = $"{r.Label} {r.Owner}".Trim(),
            Description = string.IsNullOrWhiteSpace(r.TargetPath) ? r.Evidence.Detail : $"{r.SourcePath} {r.Label} {r.TargetPath}",
            Safety = CleanupSafety.Review,
            RecommendedAction = CleanupActionKind.LeaveAlone,
            SizeBytes = 0,
            Confidence = r.Evidence.Confidence,
            Evidence = $"{r.Evidence.Source}: {r.Evidence.Detail}"
        }));

        return insights
            .OrderByDescending(i => i.SizeBytes)
            .ThenByDescending(i => i.Confidence)
            .ToList();
    }

    private static IReadOnlyList<AiCleanupRecommendation> BuildAiRecommendations(IReadOnlyList<CleanupFinding> findings)
    {
        return findings
            .Where(f => f.Safety != CleanupSafety.Blocked)
            .OrderBy(f => f.Safety)
            .ThenByDescending(f => f.SizeBytes)
            .Take(8)
            .Select(f => new AiCleanupRecommendation
            {
                SourceFindingId = f.Id,
                NodeId = f.NodeId,
                Path = f.Path,
                DisplayName = f.DisplayName,
                Category = f.Category,
                Safety = f.Safety,
                RecommendedAction = f.RecommendedAction,
                AiVerb = f.Safety switch
                {
                    CleanupSafety.Safe => f.RecommendedAction == CleanupActionKind.EmptyRecycleBin ? "Empty recycle bin" : "Clear cache",
                    CleanupSafety.UseSystemCleanup => "Run Windows cleanup",
                    _ => "Review first"
                },
                SizeBytes = f.SizeBytes,
                Confidence = Math.Min(0.98, f.Confidence),
                Reasoning = f.Safety == CleanupSafety.Safe
                    ? "Low-risk cache cleanup."
                    : "Large item with ownership or reinstall impact.",
                Evidence = f.MatchedRule,
                Guardrail = f.Safety == CleanupSafety.UseSystemCleanup
                    ? "System cleanup only; direct deletion blocked."
                    : "Path-limited; blocked/system guardrails preserved.",
                CanStage = f.Safety is CleanupSafety.Safe or CleanupSafety.Review,
                Model = "Demo Codex advisory"
            })
            .ToList();
    }

    private static void Add(
        List<FileSystemNode> nodes,
        long id,
        long? parentId,
        string name,
        string path,
        FileSystemNodeKind kind,
        long size,
        int files,
        int folders,
        string category,
        DateTimeOffset modified,
        int depth,
        string? extension = null)
    {
        nodes.Add(new FileSystemNode
        {
            Id = id,
            StableId = $"demo-{id}",
            PathHash = $"demo-path-{id}",
            ParentId = parentId,
            ParentStableId = parentId is null ? null : $"demo-{parentId}",
            Name = name,
            FullPath = path,
            Kind = kind,
            Extension = extension,
            Length = kind == FileSystemNodeKind.File ? size : 0,
            AllocatedLength = kind == FileSystemNodeKind.File ? size : 0,
            PhysicalLength = kind == FileSystemNodeKind.File ? size : 0,
            TotalLength = size,
            TotalPhysicalLength = size,
            FileCount = files,
            FolderCount = folders,
            Depth = depth,
            LastModifiedUtc = modified,
            Attributes = kind == FileSystemNodeKind.File ? FileAttributes.Archive : FileAttributes.Directory,
            Category = category,
            VolumeSerial = "DEMO-C"
        });
    }

    private static CleanupFinding Finding(
        IReadOnlyList<FileSystemNode> nodes,
        string path,
        string category,
        CleanupSafety safety,
        CleanupActionKind action,
        double confidence,
        string explanation,
        string matchedRule,
        string source,
        DateTimeOffset now)
    {
        var node = nodes.First(n => string.Equals(n.FullPath, path, StringComparison.OrdinalIgnoreCase));
        return new CleanupFinding
        {
            NodeId = node.Id,
            Path = node.FullPath,
            DisplayName = node.Name,
            Category = category,
            Safety = safety,
            RecommendedAction = action,
            SizeBytes = node.TotalPhysicalLength,
            FileCount = node.FileCount,
            LastModifiedUtc = node.LastModifiedUtc,
            Confidence = confidence,
            Explanation = explanation,
            MatchedRule = matchedRule,
            AppOrSource = source,
            Evidence = new Dictionary<string, string>
            {
                ["Path"] = node.FullPath,
                ["Size"] = node.TotalPhysicalLength.ToString(),
                ["LastSeenUtc"] = now.ToString("O")
            }
        };
    }

    private static StorageRelationship Relationship(
        Guid scanId,
        IReadOnlyList<FileSystemNode> nodes,
        string sourcePath,
        string targetPath,
        FileSystemEdgeKind kind,
        string label,
        string owner,
        string detail,
        double confidence)
    {
        var node = nodes.First(n => string.Equals(n.FullPath, sourcePath, StringComparison.OrdinalIgnoreCase));
        return new StorageRelationship
        {
            ScanId = scanId,
            SourceNodeId = node.Id,
            SourcePath = node.FullPath,
            TargetPath = targetPath,
            Kind = kind,
            Label = label,
            Owner = owner,
            Evidence = new RelationshipEvidence
            {
                Source = "Demo resolver",
                Detail = detail,
                Confidence = confidence
            }
        };
    }

    private static ChangeRecord Change(
        Guid scanId,
        IReadOnlyList<FileSystemNode> nodes,
        string path,
        ChangeKind kind,
        long previousSize,
        long currentSize,
        string reason)
    {
        var node = nodes.First(n => string.Equals(n.FullPath, path, StringComparison.OrdinalIgnoreCase));
        return new ChangeRecord
        {
            ScanId = scanId,
            StableId = node.StableId,
            Path = node.FullPath,
            Kind = kind,
            PreviousSizeBytes = previousSize,
            CurrentSizeBytes = currentSize,
            Reason = reason
        };
    }

    private static long NodeId(IReadOnlyList<FileSystemNode> nodes, string path)
    {
        return nodes.First(n => string.Equals(n.FullPath, path, StringComparison.OrdinalIgnoreCase)).Id;
    }

    private static long GiB(double value)
    {
        return (long)(value * 1024 * 1024 * 1024);
    }
}
